---
name: Actionlint
permissions:
  contents: read
on:
  pull_request:
  merge_group:
  workflow_dispatch:
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: reviewdog/action-actionlint@e37e2ca68a70112d21e135229272da28ce2d0d5a  # v1.66.1
        with:
          fail_level: any
          filter_mode: nofilter
