---
name: Actionlint
permissions:
  contents: read
on:
  pull_request:
  merge_group:
  workflow_dispatch:
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - uses: reviewdog/action-actionlint@50b75b9513baa71e6a1899a1ebaa9ac9851cf16c  # v1.66.0
        with:
          fail_level: any
          filter_mode: nofilter
